version: '3.9'
services:
  chrome:
    image: selenium/standalone-chrome:latest
    ports:
      - 4444:4444
    environment:
      - TZ=Asia/Taipei


  wtms:
    build: .
    image: flyhead/wtms:2021.0.1
    environment:
      - WTMS_URL=https://working-time-management-system-tw.internal.ericsson.com/#/login
      - WTMS_ID=ecihsia
      - WTMS_PWD=ZAQ!xsw2
      - CLOCK_ON_TIME=09:30
      - CLOCK_OUT_TIME=18:30
      - CRON_CLOCK=15:10
      - LOG_LEVEL=INFO
      - PYTHONPATH=/usr/local/src/wtms
      - TZ=Asia/Taipei
    volumes:
      - ./wtms:/usr/local/src/wtms
    command: "python /usr/local/src/wtms/app.py"
    depends_on:
      - chrome
